# docker compose -f compose.yml up --build
services:
  fine-tuning:
    build:
      context: .
      dockerfile: Dockerfile
    image: fine-tuning
    stdin_open: true
    tty: true
    environment:
      MODEL_BASE_ID: unsloth/qwen2.5-1.5b-instruct
      #TRAINING_DATA_PATH: data/training_data.json
      TRAINING_DATA_PATH: data/training_queen_pedauque_training_data.json
      SOURCE_MODEL_FILE: qwen2.5-1.5b-instruct.F16.gguf
      OUTPUT_MODEL_FILE: fine-tuned-model.F16.gguf
    volumes:
      - ./output:/usr/local/app/gguf_output
      - ./data:/usr/local/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
